In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder , MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [45]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [46]:
train

,Name,Gender,Age,Math,Science,English,Attendance,StudyHours,PreviousMarks,Target
0,Olivia0,Female,21.0,26.0,29.0,88.0,56.0,6.0,94.0,0
1,Allen1,Male,16.0,31.0,75.0,73.0,54.0,4.0,31.0,1
2,Sophia2,Male,17.0,100.0,100.0,94.0,53.0,10.0,94.0,1
3,Noah3,Male,16.0,91.0,37.0,57.0,76.0,NaN,89.0,1
4,John4,Male,16.0,94.0,93.0,44.0,73.0,2.0,90.0,1
...,...,...,...,...,...,...,...,...,...,...
995,Sophia995,Female,21.0,82.0,72.0,62.0,68.0,4.0,78.0,1
996,Mia996,Female,19.0,30.0,57.0,34.0,80.0,3.0,64.0,0
997,Emma997,Female,17.0,49.0,51.0,43.0,79.0,3.0,94.0,0
998,David998,Male,21.0,83.0,NaN,97.0,98.0,9.0,76.0,1
999,John999,Female,18.0,34.0,29.0,31.0,400.0,2.0,67.0,0

In [47]:
test

,Name,Gender,Age,Math,Science,English,Attendance,StudyHours,PreviousMarks
0,Mia0,Female,16.0,41.0,48.0,98.0,57.0,9.0,75.0
1,Sophia1,Female,22.0,82.0,25.0,47.0,80.0,2.0,47.0
2,John2,Male,NaN,94.0,79.0,48.0,-30.0,8.0,42.0
3,Noah3,Male,21.0,250.0,93.0,57.0,79.0,1.0,NaN
4,Olivia4,Male,18.0,83.0,27.0,35.0,59.0,6.0,87.0
...,...,...,...,...,...,...,...,...,...
195,Emma195,Male,18.0,21.0,26.0,92.0,89.0,8.0,NaN
196,Sophia196,Male,19.0,62.0,22.0,40.0,85.0,6.0,37.0
197,John197,Female,18.0,NaN,NaN,92.0,62.0,7.0,65.0
198,Liam198,Female,22.0,62.0,87.0,88.0,69.0,NaN,52.0
199,Mia199,Male,19.0,-30.0,98.0,71.0,95.0,8.0,76.0

In [48]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           1000 non-null   object
 1   Gender         980 non-null    object
 2   Age            950 non-null    float64
 3   Math           950 non-null    float64
 4   Science        951 non-null    float64
 5   English        950 non-null    float64
 6   Attendance     951 non-null    float64
 7   StudyHours     950 non-null    float64
 8   PreviousMarks  950 non-null    float64
 9   Target         1000 non-null   int64
dtypes: float64(7), int64(1), object(2)
memory usage: 78.3+ KB

In [49]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           200 non-null    object
 1   Gender         198 non-null    object
 2   Age            190 non-null    float64
 3   Math           190 non-null    float64
 4   Science        191 non-null    float64
 5   English        190 non-null    float64
 6   Attendance     190 non-null    float64
 7   StudyHours     190 non-null    float64
 8   PreviousMarks  190 non-null    float64
dtypes: float64(7), object(2)
memory usage: 14.2+ KB

In [50]:
train.isna().sum()

Name              0
Gender           20
Age              50
Math             50
Science          49
English          50
Attendance       49
StudyHours       50
PreviousMarks    50
Target            0
dtype: int64

In [51]:
col = ['Age','Math','Science','English','Attendance','StudyHours','PreviousMarks']

train[col] = train[col].fillna(train[col].mean())
train['Gender'] = train['Gender'].fillna(train['Gender'].mode()[0])

In [52]:
train['Gender'].value_counts()

Gender
Female    514
Male      486
Name: count, dtype: int64

In [53]:
test.isna().sum()

Name              0
Gender            2
Age              10
Math             10
Science           9
English          10
Attendance       10
StudyHours       10
PreviousMarks    10
dtype: int64

In [54]:
col = ['Age','Math','Science','English','Attendance','StudyHours','PreviousMarks']

test[col] = test[col].fillna(test[col].mean())
test['Gender'] = test['Gender'].fillna(test['Gender'].mode()[0])

In [56]:
le = LabelEncoder()
mm = MinMaxScaler()
for i in train.columns:
    if train[i].dtype == 'object':
        train[i]=le.fit_transform(train[i])

for i in test.columns:
    if test[i].dtype == 'object':
        test[i]=le.fit_transform(test[i])

In [57]:
train.iloc[:,:-1]=mm.fit_transform(train.iloc[:,:-1])
test.iloc[:,:]=mm.transform(test.iloc[:,:])

C:\Users\prath\AppData\Local\Temp\ipykernel_9304\3216951432.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.67367367 0.         0.91491491 0.58458458 0.32132132 0.33333333
 0.73573574 0.74374374 0.26026026 0.77577578 0.08508509 0.49449449
 0.2962963  0.67967968 0.003003   0.4994995  0.57057057 0.18018018
 0.5045045  0.41241241 0.68668669 0.18618619 0.68768769 0.7987988
 0.68968969 0.42142142 0.69169169 0.19319319 0.1951952  0.6986987
 0.8048048  0.7017017  0.58958959 0.51951952 0.02102102 0.02202202
 0.52352352 0.11811812 0.70970971 0.71171171 0.20720721 0.03003003
 0.93693694 0.21021021 0.53053053 0.03403403 0.03603604 0.21721722
 0.45245245 0.94494494 0.94794795 0.61361361 0.22122122 0.04204204
 0.72572573 0.45745746 0.62162162 0.95495495 0.13313313 0.95595596
 0.73673674 0.95895896 0.34934935 0.85685686 0.54254254 0.54454454
 0.14114114 0.35435435 0.86286286 0.74274274 0.24924925 0.74674675
 0.36036036 0.64164164 0.14714715 0.64364364 0.55255255 0.75475475
 0.64664665 0.75775776 0.76176176 0.65365365 0.76576577 0.15515516
 0.37737738 0.37937938 0.55855856 0.38238238 0.07307307 0.89089089
 0.38838839 0.77777778 0.16216216 0.56256256 0.07707708 0.3953954
 0.16616617 0.3983984  0.67067067 0.49249249 0.29429429 0.67467467
 0.001001   0.4034034  0.67567568 0.002002   0.78478478 0.49349349
 0.08608609 0.08708709 0.78578579 0.4044044  0.78678679 0.4954955
 0.08808809 0.4964965  0.56856857 0.08908909 0.67667668 0.2952953
 0.90590591 0.17117117 0.09009009 0.4974975  0.17217217 0.78778779
 0.40540541 0.67767768 0.40640641 0.67867868 0.17317317 0.17417417
 0.78878879 0.17517518 0.68068068 0.2972973  0.09109109 0.68168168
 0.90690691 0.56956957 0.004004   0.4984985  0.78978979 0.00500501
 0.17617618 0.00600601 0.90790791 0.00700701 0.40740741 0.09209209
 0.90890891 0.5005005  0.09309309 0.00800801 0.2982983  0.2992993
 0.3003003  0.09409409 0.5015015  0.90990991 0.0950951  0.5025025
 0.17717718 0.57157157 0.91091091 0.00900901 0.40840841 0.79079079
 0.17817818 0.17917918 0.79179179 0.0960961  0.5035035  0.40940941
 0.18118118 0.68268268 0.18218218 0.41041041 0.91191191 0.57257257
 0.79279279 0.3013013  0.0970971  0.57357357 0.41141141 0.50550551
 0.3023023  0.68368368 0.91291291 0.91391391 0.41341341 0.68468468
 0.18318318 0.41441441 0.68568569 0.0980981  0.41541542 0.57457457
 0.01001001 0.18418418 0.18518519 0.0990991  0.01101101 0.3033033
 0.3043043  0.30530531 0.79379379 0.41641642 0.57557558 0.41741742
 0.57657658 0.50650651 0.57757758 0.1001001  0.91591592 0.79479479
 0.50750751 0.57857858 0.7957958  0.91691692 0.18718719 0.7967968
 0.30630631 0.01201201 0.30730731 0.68868869 0.01301301 0.1011011
 0.30830831 0.7977978  0.30930931 0.7997998  0.18818819 0.50850851
 0.41841842 0.8008008  0.18918919 0.19019019 0.50950951 0.51051051
 0.1021021  0.1031031  0.19119119 0.91791792 0.01401401 0.19219219
 0.91891892 0.41941942 0.42042042 0.8018018  0.57957958 0.58058058
 0.69069069 0.31031031 0.01501502 0.51151151 0.1041041  0.51251251
 0.10510511 0.58158158 0.01601602 0.69269269 0.10610611 0.91991992
 0.69369369 0.42242242 0.31131131 0.42342342 0.69469469 0.10710711
 0.51351351 0.42442442 0.42542543 0.6956957  0.6966967  0.19419419
 0.10810811 0.31231231 0.10910911 0.51451451 0.92092092 0.51551552
 0.11011011 0.51651652 0.8028028  0.58258258 0.58358358 0.1961962
 0.6976977  0.42642643 0.1971972  0.6996997  0.8038038  0.92192192
 0.01701702 0.7007007  0.31331331 0.42742743 0.01801802 0.31431431
 0.80580581 0.80680681 0.51751752 0.58558559 0.58658659 0.80780781
 0.1981982  0.58758759 0.92292292 0.51851852 0.80880881 0.11111111
 0.7027027  0.11211211 0.31531532 0.58858859 0.7037037  0.80980981
 0.42842843 0.1991992  0.01901902 0.92392392 0.11311311 0.7047047
 0.02002002 0.2002002  0.2012012  0.42942943 0.11411411 0.92492492
 0.43043043 0.2022022  0.59059059 0.2032032  0.70570571 0.92592593
 0.52052052 0.31631632 0.59159159 0.43143143 0.43243243 0.92692693
 0.70670671 0.81081081 0.59259259 0.92792793 0.11511512 0.92892893
 0.43343343 0.43443443 0.11611612 0.52152152 0.11711712 0.43543544
 0.52252252 0.92992993 0.43643644 0.43743744 0.02302302 0.31731732
 0.52452452 0.93093093 0.2042042  0.93193193 0.02402402 0.70770771
 0.81181181 0.59359359 0.52552553 0.02502503 0.02602603 0.11911912
 0.31831832 0.02702703 0.81281281 0.43843844 0.31931932 0.20520521
 0.70870871 0.59459459 0.5955956  0.52652653 0.5965966  0.43943944
 0.5975976  0.93293293 0.81381381 0.71071071 0.5985986  0.93393393
 0.44044044 0.44144144 0.93493493 0.71271271 0.81481481 0.12012012
 0.20620621 0.32032032 0.52752753 0.5995996  0.93593594 0.02802803
 0.44244244 0.71371371 0.6006006  0.12112112 0.02902903 0.44344344
 0.71471471 0.52852853 0.20820821 0.44444444 0.32232232 0.6016016
 0.52952953 0.6026026  0.81581582 0.81681682 0.81781782 0.12212212
 0.71571572 0.44544545 0.32332332 0.03103103 0.20920921 0.32432432
 0.44644645 0.81881882 0.03203203 0.6036036  0.81981982 0.82082082
 0.21121121 0.93793794 0.32532533 0.82182182 0.21221221 0.44744745
 0.32632633 0.82282282 0.82382382 0.53153153 0.21321321 0.71671672
 0.03303303 0.71771772 0.21421421 0.71871872 0.44844845 0.44944945
 0.21521522 0.82482482 0.93893894 0.71971972 0.03503504 0.21621622
 0.72072072 0.93993994 0.94094094 0.12312312 0.72172172 0.32732733
 0.6046046  0.12412412 0.82582583 0.94194194 0.12512513 0.32832833
 0.12612613 0.32932933 0.94294294 0.94394394 0.60560561 0.45045045
 0.33033033 0.82682683 0.72272272 0.21821822 0.60660661 0.45145145
 0.12712713 0.60760761 0.53253253 0.33133133 0.82782783 0.45345345
 0.82882883 0.60860861 0.82982983 0.83083083 0.03703704 0.94594595
 0.94694695 0.03803804 0.60960961 0.33233233 0.83183183 0.61061061
 0.61161161 0.12812813 0.53353353 0.83283283 0.21921922 0.45445445
 0.83383383 0.53453453 0.83483483 0.33433433 0.33533534 0.61261261
 0.61461461 0.83583584 0.45545546 0.33633634 0.72372372 0.22022022
 0.83683684 0.83783784 0.33733734 0.83883884 0.94894895 0.03903904
 0.45645646 0.83983984 0.04004004 0.53553554 0.04104104 0.12912913
 0.84084084 0.84184184 0.61561562 0.13013013 0.33833834 0.22222222
 0.22322322 0.13113113 0.94994995 0.95095095 0.61661662 0.72472472
 0.61761762 0.72672673 0.33933934 0.72772773 0.61861862 0.72872873
 0.04304304 0.04404404 0.84284284 0.95195195 0.22422422 0.95295295
 0.13213213 0.84384384 0.61961962 0.62062062 0.95395395 0.22522523
 0.04504505 0.22622623 0.72972973 0.62262262 0.73073073 0.04604605
 0.62362362 0.34034034 0.62462462 0.34134134 0.84484484 0.04704705
 0.84584585 0.53653654 0.53753754 0.84684685 0.62562563 0.22722723
 0.45845846 0.73173173 0.84784785 0.73273273 0.34234234 0.34334334
 0.34434434 0.84884885 0.73373373 0.62662663 0.04804805 0.22822823
 0.13413413 0.22922923 0.23023023 0.62762763 0.23123123 0.84984985
 0.45945946 0.46046046 0.95695696 0.73473473 0.04904905 0.23223223
 0.53853854 0.34534535 0.95795796 0.62862863 0.13513514 0.85085085
 0.34634635 0.85185185 0.23323323 0.23423423 0.34734735 0.05005005
 0.95995996 0.05105105 0.23523524 0.85285285 0.85385385 0.96096096
 0.05205205 0.34834835 0.13613614 0.35035035 0.53953954 0.13713714
 0.05305305 0.35135135 0.96196196 0.85485485 0.85585586 0.96296296
 0.23623624 0.54054054 0.13813814 0.85785786 0.85885886 0.54154154
 0.85985986 0.35235235 0.23723724 0.96396396 0.13913914 0.62962963
 0.23823824 0.54354354 0.63063063 0.63163163 0.23923924 0.14014014
 0.96496496 0.05405405 0.63263263 0.86086086 0.73773774 0.24024024
 0.46146146 0.46246246 0.05505506 0.73873874 0.24124124 0.63363363
 0.73973974 0.46346346 0.14214214 0.05605606 0.96596597 0.46446446
 0.63463463 0.74074074 0.35335335 0.24224224 0.24324324 0.63563564
 0.96696697 0.35535536 0.54554555 0.74174174 0.86186186 0.63663664
 0.46546547 0.54654655 0.86386386 0.96796797 0.35635636 0.54754755
 0.24424424 0.05705706 0.24524525 0.63763764 0.24624625 0.96896897
 0.86486486 0.46646647 0.54854855 0.86586587 0.05805806 0.24724725
 0.05905906 0.24824825 0.86686687 0.46746747 0.46846847 0.86786787
 0.74474474 0.06006006 0.25025025 0.35735736 0.14314314 0.86886887
 0.35835836 0.74574575 0.35935936 0.14414414 0.74774775 0.46946947
 0.96996997 0.54954955 0.86986987 0.06106106 0.63863864 0.74874875
 0.06206206 0.06306306 0.36136136 0.63963964 0.36236236 0.74974975
 0.64064064 0.36336336 0.06406406 0.36436436 0.36536537 0.55055055
 0.14514515 0.47047047 0.87087087 0.87187187 0.14614615 0.47147147
 0.75075075 0.25125125 0.25225225 0.25325325 0.75175175 0.14814815
 0.64264264 0.47247247 0.06506507 0.97097097 0.87287287 0.97197197
 0.97297297 0.36636637 0.75275275 0.36736737 0.25425425 0.06606607
 0.06706707 0.64464464 0.97397397 0.55155155 0.14914915 0.36836837
 0.06806807 0.25525526 0.87387387 0.64564565 0.06906907 0.75375375
 0.36936937 0.87487487 0.75575576 0.15015015 0.87587588 0.25625626
 0.37037037 0.47347347 0.47447447 0.87687688 0.37137137 0.87787788
 0.64764765 0.75675676 0.15115115 0.64864865 0.64964965 0.37237237
 0.25725726 0.47547548 0.87887888 0.25825826 0.97497497 0.65065065
 0.25925926 0.37337337 0.75875876 0.47647648 0.75975976 0.76076076
 0.87987988 0.88088088 0.37437437 0.76276276 0.15215215 0.65165165
 0.88188188 0.55355355 0.65265265 0.15315315 0.26126126 0.97597598
 0.47747748 0.26226226 0.76376376 0.88288288 0.76476476 0.47847848
 0.88388388 0.26326326 0.15415415 0.55455455 0.37537538 0.65465465
 0.47947948 0.88488488 0.26426426 0.97697698 0.76676677 0.97797798
 0.65565566 0.97897898 0.48048048 0.76776777 0.88588589 0.26526527
 0.88688689 0.07007007 0.55555556 0.55655656 0.37637638 0.15615616
 0.55755756 0.65665666 0.97997998 0.98098098 0.37837838 0.88788789
 0.07107107 0.88888889 0.76876877 0.15715716 0.26626627 0.15815816
 0.48148148 0.76976977 0.98198198 0.48248248 0.98298298 0.98398398
 0.65765766 0.15915916 0.16016016 0.77077077 0.65865866 0.38038038
 0.07207207 0.98498498 0.98598599 0.26726727 0.77177177 0.38138138
 0.98698699 0.88988989 0.65965966 0.16116116 0.55955956 0.48348348
 0.77277277 0.38338338 0.38438438 0.98798799 0.77377377 0.66066066
 0.98898899 0.38538539 0.98998999 0.38638639 0.26826827 0.26926927
 0.07407407 0.38738739 0.27027027 0.99099099 0.27127127 0.27227227
 0.89189189 0.27327327 0.27427427 0.89289289 0.77477477 0.07507508
 0.66166166 0.27527528 0.77677678 0.48448448 0.99199199 0.66266266
 0.27627628 0.48548549 0.89389389 0.38938939 0.07607608 0.66366366
 0.99299299 0.56056056 0.27727728 0.89489489 0.77877878 0.39039039
 0.99399399 0.56156156 0.39139139 0.66466466 0.27827828 0.8958959
 0.8968969  0.39239239 0.66566567 0.27927928 0.66666667 0.48648649
 0.48748749 0.99499499 0.28028028 0.28128128 0.56356356 0.995996
 0.66766767 0.28228228 0.39339339 0.16316316 0.28328328 0.56456456
 0.28428428 0.16416416 0.28528529 0.77977978 0.56556557 0.8978979
 0.996997   0.39439439 0.78078078 0.8988989  0.16516517 0.07807808
 0.8998999  0.66866867 0.66966967 0.48848849 0.48948949 0.9009009
 0.9019019  0.28628629 0.9029029  0.07907908 0.78178178 0.28728729
 0.08008008 0.3963964  0.28828829 0.3973974  0.28928929 0.78278278
 0.16716717 0.29029029 0.16816817 0.49049049 0.16916917 0.08108108
 0.49149149 0.997998   0.56656657 0.3993994  0.78378378 0.4004004
 0.67167167 0.08208208 0.9039039  0.29129129 0.998999   0.08308308
 0.4014014  0.29229229 0.08408408 0.67267267 0.9049049  1.
 0.56756757 0.29329329 0.17017017 0.4024024 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  train.iloc[:,:-1]=mm.fit_transform(train.iloc[:,:-1])
C:\Users\prath\AppData\Local\Temp\ipykernel_9304\3216951432.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.09109109 0.17217217 0.05605606 0.12312312 0.15115115 0.01001001
 0.01201201 0.04304304 0.1971972  0.08908909 0.13213213 0.17617618
 0.11611612 0.13813814 0.04604605 0.07507508 0.01901902 0.03503504
 0.02102102 0.07807808 0.05705706 0.14814815 0.04004004 0.05805806
 0.14914915 0.10810811 0.15015015 0.02202202 0.02302302 0.18918919
 0.12412412 0.12512513 0.19019019 0.10910911 0.05905906 0.02402402
 0.06006006 0.19119119 0.04104104 0.00700701 0.11011011 0.06106106
 0.08108108 0.02502503 0.00800801 0.00900901 0.06206206 0.06306306
 0.04204204 0.11111111 0.19219219 0.16316316 0.12612613 0.08208208
 0.19319319 0.15215215 0.01101101 0.16416416 0.16516517 0.12712713
 0.16616617 0.06406406 0.01301301 0.16716717 0.08308308 0.15315315
 0.08408408 0.12812813 0.19419419 0.06506507 0.11211211 0.06606607
 0.15415415 0.1951952  0.1961962  0.04404404 0.01401401 0.15515516
 0.01501502 0.08508509 0.06706707 0.01601602 0.02602603 0.08608609
 0.01701702 0.08708709 0.08808809 0.16816817 0.1981982  0.12912913
 0.04504505 0.16916917 0.09009009 0.15615616 0.13013013 0.1991992
 0.13113113 0.11311311 0.17017017 0.17117117 0.02702703 0.17317317
 0.02802803 0.06806807 0.17417417 0.06906907 0.09209209 0.11411411
 0.07007007 0.17517518 0.07107107 0.17717718 0.13313313 0.11511512
 0.         0.02902903 0.03003003 0.09309309 0.13413413 0.13513514
 0.13613614 0.09409409 0.13713714 0.001001   0.07207207 0.03103103
 0.0950951  0.0960961  0.0970971  0.07307307 0.13913914 0.01801802
 0.002002   0.03203203 0.0980981  0.0990991  0.07407407 0.17817818
 0.15715716 0.14014014 0.17917918 0.14114114 0.04704705 0.04804805
 0.03303303 0.15815816 0.18018018 0.03403403 0.04904905 0.14214214
 0.003003   0.004004   0.11711712 0.11811812 0.1001001  0.15915916
 0.07607608 0.16016016 0.00500501 0.1011011  0.18118118 0.1021021
 0.1031031  0.16116116 0.18218218 0.11911912 0.05005005 0.18318318
 0.18418418 0.18518519 0.00600601 0.05105105 0.12012012 0.14314314
 0.14414414 0.02002002 0.07707708 0.18618619 0.12112112 0.05205205
 0.03603604 0.03703704 0.14514515 0.18718719 0.12212212 0.1041041
 0.05305305 0.14614615 0.03803804 0.10510511 0.05405405 0.14714715
 0.10610611 0.16216216 0.07907908 0.03903904 0.18818819 0.05505506
 0.08008008 0.10710711]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  test.iloc[:,:]=mm.transform(test.iloc[:,:])

In [58]:
X = train.iloc[:,:-1]
Y = train['Target']

In [59]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

model.fit(X,Y)
model

LinearRegression()

In [ ]:

X_test = test

predictions = model.predict(X_test)

print(predictions)

Fold Accuracies: [0.88  0.905 0.885 0.83  0.905]
Average Accuracy: 0.881